### ISSUE TITLE
Question about the usage of pycg in this project

### ISSUE THREAD

**Issue by JIANG-CX** [nv-tlabs/NKSR#13]
Wonderful work!
"I have some questions about the "pycg" package that is used in this project. Are there any special properties that differentiate it from the original "open3d" package? Also, is there any usage guidance available for "pycg"? I have only found this link: https://pycg.readthedocs.io/en/latest/, but it does not provide much guidance." 
Thanks

**Comment by heiwang1997** [comment]
Hey thanks for your interest in our work!

Basically `pycg` is a utility package, and `pycg.vis` is a wrapper of Open3D that simplifies its API for fast visualization and rendering. The customized version (source code available at https://github.com/heiwang1997/Open3D) of Open3D differentiates from the official version in that I've incorporated many changes that supports multi-window camera synchronization, animation, scalar analyzer, ... I think you can use the official Open3D and it will also work fine!

Sorry I failed to find a good time to write docs for `pycg` -- I will try to populate the doc next week :)

**Comment by rohitdhote111** [comment]
how to save colored mesh using pycg vis?

**Comment by heiwang1997** [comment]
https://github.com/nv-tlabs/NKSR/issues/3#issuecomment-1585991146

```
vis.to_file(vis.mesh(mesh.v, mesh.f, color=mesh.c), "a.ply")
```

Please note that `pycg.vis` is not a necessity for visualization. You can keep using your favourite 3d visualization library.

**Comment by JIANG-CX** [comment]
Thanks for your answer! (*^▽^*)
