### ISSUE TITLE
About data preparation

### ISSUE THREAD

**Issue by lazy2001** [nv-tlabs/NKSR#18]
Great work!!!I am trying to do some interesting work with NKSR.But i am just a freshman in 3d reconstruction field.Could you give me some suggestions on how to obtain high-quality normal vectors from point clouds？I think this will be very helpful for my future studies.Really great work!

**Comment by fwilliams** [comment]
Hi, this is a great question. If your point clouds are coming from a sensor you should be able to extract the position of the sensor for each point in the scan (from the registration process). This should be sufficient to orient normals. You can also feed this sensor direction into NKSR without computing normals directly. Hope this helps!

**Comment by lazy2001** [comment]
Thank you very much for your reply!I hope i can do some interesting work with NKSR!

**Comment by fwilliams** [comment]
What point clouds are you trying this on?

**Comment by lazy2001** [comment]
Individual tooth point clouds, I tried to obtain point clouds by Structured light scanning in the laboratory.The quality of my data is relatively low.HAHA.
