### ISSUE TITLE
How to Obtain the input_sensor Information

### ISSUE THREAD

**Issue by Zhimin-C** [nv-tlabs/NKSR#19]
Thanks for the great work! I want to apply the method on the point cloud collected from Velodyne lidar. May you tell me how to obtain the input_sensor information from the kitti format? Thanks.

**Comment by heiwang1997** [comment]
Yes! Here is some pseudo-code for doing that:
```
xyz_list = []
sensor_list = []
for frame_idx in range(1000):
    xyz = load_kitti_lidar(frame_idx)
    pose = load_kitti_pose(frame_idx)
    xyz_list.append(pose.transform(xyz))
    sensor_list.append(pose.transform([[0,0,0] for _ in range(xyz.shape[0])]))
xyz = np.concatenate(xyz_list)
sensor = np.concatenate(sensor_list)
```

For more details, could you refer to #3? Thanks

**Comment by Zhimin-C** [comment]
Thanks!
