### ISSUE TITLE
Estimate GPU memory required

### ISSUE THREAD

**Issue by devloper13** [nv-tlabs/NKSR#20]
My point cloud data consisting of points and normal is about 650 MB big (ply format). Is there a way to approximate how much GPU memory is required for mesh extraction. My system has 12GB yet it fails. And CPU takes a long time.

Thank you!

**Comment by heiwang1997** [comment]
An accurate estimation is actually challenging to obtain here -- it depends on the point distribution, scale, and so on. In our test cases, we've successfully reconstructed a >3GB point cloud using a 24GB GPU. Have you tried using chunked mode?

**Comment by devloper13** [comment]
Yes I did it using the chunking script. I made it work on a more ram stuffed machine and it worked for now :)

**Comment by fwilliams** [comment]
Great! Glad it worked!
