### ISSUE TITLE
New Pretrain PTh Other than ks.pth

### ISSUE THREAD

**Issue by LeonardPatrick** [nv-tlabs/NKSR#24]
Hi, I am working on a parking lot map reconstruction. The performance of NKSR is excellent, while not accurate in some details. I wonder whether there is other .pth file, for instance, outdoor case. Thank you very much.

**Comment by heiwang1997** [comment]
Hi sorry for missing this one. Other pretrained models should be available using links [here](https://github.com/nv-tlabs/NKSR#inference).
