### ISSUE TITLE
NKSR On Windows

### ISSUE THREAD

**Issue by Junking1** [nv-tlabs/NKSR#25]
When I ran test.py from source code, I encountered an error that there was no nksr library, but when I checked the repository, I found that nksr was only available in linux, so does it only support the linux platform at present? Is there any other way to run on the windows platform other than docker?

**Comment by fwilliams** [comment]
Right now, it's Linux only yes. We would love help porting things to work on Windows though!

**Comment by Junking1** [comment]
Thank you very much. I tried to use WSL2, and it worked.
Still looking forward to the Windows version.

**Comment by fwilliams** [comment]
Cool that it works on WSL2!

**Comment by fwilliams** [comment]
I think for now, WSL is the solution for Windows.
