### ISSUE TITLE
How to save the mesh instead of showing on line?

### ISSUE THREAD

**Issue by rockywind** [nv-tlabs/NKSR#3]
Hi, thank you for sharing the code.
I run the code on the server so I haven't the monitor to show the result.
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/6f9c4489-63d2-4542-bb09-1d799bab935f)

**Comment by heiwang1997** [comment]
Here is the thing you can do! :) 

```bash
vis.to_file(vis.mesh(mesh.v, mesh.f), "a.ply")
```

**Comment by rockywind** [comment]
Thank you very much!

**Comment by rockywind** [comment]
Hi, 
Can you sharing the waymo-pcd.ply?
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/8f63ec1d-4e54-4083-ab3b-701d7584cb72)

**Comment by heiwang1997** [comment]
Oops sorry for making a mistake in the common script! I've pushed a fix. Feel free to pull and check again. The file should be automatically downloaded.

**Comment by rockywind** [comment]
Hi, 
I want to run the code on my own data, my data style is the same as  Kitti.
Can you give me some tutorial.
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/4d556600-63e6-4415-a606-c5c728f4a82d)

**Comment by heiwang1997** [comment]
We haven't tested on KITTI dataset yet. But it should be easy! Some pseudo-code look like:

```
xyz_list = []
sensor_list = []
for frame_idx in range(1000):
    xyz = load_kitti_lidar(frame_idx)
    pose = load_kitti_pose(frame_idx)
    xyz_list.append(pose.transform(xyz))
    sensor_list.append(pose.transform([[0,0,0] for _ in range(xyz.shape[0])]))
xyz = np.concatenate(xyz_list)
sensor = np.concatenate(sensor_list)
```

Hope this helps!

**Comment by rockywind** [comment]
Thank you very much!

**Comment by rockywind** [comment]
How to add the color to the mesh on waymo dataset?
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/62831a0a-f303-43d3-97b6-04cfc7147f3b)

**Comment by rockywind** [comment]
@heiwang1997 
Hi,
I confuse with the setting of **sensor** on kitti dataset.
I think the xyz is in world coordinate and the sensor is velo_to_world's translation.
The value of sensor is the same for all point clouds.
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/e9b1ce64-44c3-4476-b379-9fe634c981de)

The below is the reconstruction of kitti dataset.
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/8171c3f5-b787-4b43-9b57-9c023be9e98c)

**Comment by heiwang1997** [comment]
Hi thanks for the questions.

1. In the paper we didn't really show the color of the mesh, instead what we showed is the normal map, where the RGB color is actually the XYZ component of the normals. We use `Open3D` to visualize our mesh, and if you press `Ctrl+9` on your keyboard, you should be able to see the normal map we've drawn on the paper.
2. Do you mean `base_pose` is the same for all input frames? That means your car is static I guess. Could you maybe visualize the positions of the sensors as well as the points just for debugging purposes?

Best.

**Comment by rockywind** [comment]
@heiwang1997 
您好，感谢您的解答。我用中文提问会更清晰。
1. 自车是运动的，senseor(base_pose)值是取第0帧的velo_to_world的translation(矩阵的第4列)，对所有的输入帧base_pose的值是一样的。
因为我把第一帧当做世界坐标的原点。
2. 另一个思路是，senseor(base_pose)值取每个输入帧的velo_to_world的translation(矩阵的第4列)。对所有的输入帧base_pose的值是不一样的，每一帧的sensor值是其对应的velo_to_world的translation(矩阵的第四列)。
下图是采用第一种（1）做法的结果
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/617c411d-96ac-497a-aae9-574ca20cd0eb)
下图是采用第二种（2）方法的结果
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/c0808fbe-03ac-4d8a-ba41-c35b2fedb950)

**Comment by heiwang1997** [comment]
您好，我对您的第二点不是太理解，为何“senseor(base_pose)值取**每个输入帧**的velo_to_world”，但“对所有的输入帧base_pose的值**是一样的**”呢？可以理解为所有的输入帧的pose都是一样的吗？

另外，KITTI数据集噪声比较大，可以尝试提升一下Normal estimation knn的值～

**Comment by rockywind** [comment]
您好，之前描述有错误，已经修改了。
您觉得这两种做法有什么问题吗？

**Comment by heiwang1997** [comment]
好的，谢谢！
我觉得第二种做法应该是没问题的，如果觉得噪声比较大，可以尝试两种方案：
1. 提升一下Normal estimation knn的值，就是 `get_estimate_normal_preprocess_fn `的第一个参数；
2. 另一个trick是吧sensor的位置全局调高一些，然后每一帧crop掉距离较远的点。

**Comment by rockywind** [comment]
十分感谢，我还有两个问题请教哈
1. 如果velo_to_world的矩阵的第一帧是单位矩阵，就是每帧的velo_to_world左乘第一帧的velo_to_world的逆矩阵，把第一帧为全局坐标的参考,这样做可以吗。[inverse(velo_to_world[0]) @ velo_to_world[i] for i in range(velo_to_world)]
2. repo里面的waymo-pcd.ply的重建效果很好，想问一下是单帧点云的效果，还是多帧点云合并的，如果是多帧合并，大概是几帧合并的？

**Comment by heiwang1997** [comment]
不客气的～有关你的问题：

1. 我不太清楚 `velo_to_world` 矩阵具体是pose还是pose的逆，只要能将激光雷达局部坐标系的点云变换到世界坐标系下即可，变换后尽可能Z轴朝上，因为我们的默认模型训练数据都是Z轴朝上的；
2. waymo是多帧点云合并的效果，我们总共使用了150帧左右的waymo数据（但中间有跳帧，每隔2帧选一帧）

**Comment by rockywind** [comment]
十分感谢，
1. velo_to_world是激光雷达坐标系转世界坐标系：point_in_world = velo_to_world(4*4) @ point_in_lidar(4*N)。
2. 我们把第一帧的pose当做参考帧，`[inverse(velo_to_world[0]) @ velo_to_world[i] for i in range(velo_to_world)]`

**Comment by YuePanEdward** [comment]
I've got some quite good results on KITTI and Newer College datasets using NKSR and the reconstruction is also super fast (in about 10 seconds)
![Screenshot from 2023-06-12 15-04-28](https://github.com/nv-tlabs/NKSR/assets/34207278/99ef94d1-5974-47ef-b187-79dfe5c37ce0)
![Screenshot from 2023-06-12 15-08-02](https://github.com/nv-tlabs/NKSR/assets/34207278/95f67570-39e3-4577-88a3-96a111c4abfe)

**Comment by rockywind** [comment]
@YuePanEdward 
Hi, 
Can you share the code on KITTI dataset?

**Comment by YuePanEdward** [comment]
You can try to add [this](https://gist.github.com/YuePanEdward/c8f83e65191ea02fcf12d1c3fa352026) to common.py.

And then replace ```xyz_np, sensor_np = load_waymo_example()``` with 
```xyz_np, sensor_np = load_kitti_like_data(pc_folder, pose_file, calib_file, every_n_frame=1, begin_frame=0, end_frame=100)``` and provide the correct path to your dataset.
 
For the visualization, you may use open3d:
```
import open3d as o3d
mesh_v, mesh_f = mesh.v.detach().cpu().numpy(), mesh.f.detach().cpu().numpy()
mesh = o3d.geometry.TriangleMesh(o3d.utility.Vector3dVector(mesh_v), o3d.utility.Vector3iVector(mesh_f))
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([mesh])
o3d.io.write_triangle_mesh(your_mesh_path, mesh)
```

**Comment by qpc001** [comment]
> I've got some quite good results on KITTI and Newer College datasets using NKSR and the reconstruction is also super fast (in about 10 seconds) ![Screenshot from 2023-06-12 15-04-28](https://user-images.githubusercontent.com/34207278/245153736-99ef94d1-5974-47ef-b187-79dfe5c37ce0.png) ![Screenshot from 2023-06-12 15-08-02](https://user-images.githubusercontent.com/34207278/245153814-95f67570-39e3-4577-88a3-96a111c4abfe.png) I wonder if the nksr lib will also be made open-source? The marching cubes algorithm implemented there seems to be super fast.
> 

How can you reconstruct large scale like kitti without CUDA out of Memory?

**Comment by fwilliams** [comment]
Hey wow @YuePanEdward these look amazing! 

Any chance you want to send a PR with an example script for these datasets? This would be greatly appreciated by the community!

Also if you want to win a free GPU, feel free to upload anything cool you do here for the contest: [nvda.ws/3NkPYs5](https://t.co/qyqZ5TMxFz)

**Comment by rockywind** [comment]
> You can try to add [this](https://gist.github.com/YuePanEdward/c8f83e65191ea02fcf12d1c3fa352026) to common.py.
> 
> And then replace `xyz_np, sensor_np = load_waymo_example()` with `xyz_np, sensor_np = load_kitti_like_data(pc_folder, pose_file, calib_file, every_n_frame=1, begin_frame=0, end_frame=100)` and provide the correct path to your dataset.
> 
> For the visualization, you may use open3d:
> 
> ```
> import open3d as o3d
> mesh_v, mesh_f = mesh.v.detach().cpu().numpy(), mesh.f.detach().cpu().numpy()
> mesh = o3d.geometry.TriangleMesh(o3d.utility.Vector3dVector(mesh_v), o3d.utility.Vector3iVector(mesh_f))
> mesh.compute_vertex_normals()
> o3d.visualization.draw_geometries([mesh])
> o3d.io.write_triangle_mesh(your_mesh_path, mesh)
> ```
您好请问一下，能解释一下[这段代码](https://gist.github.com/YuePanEdward/c8f83e65191ea02fcf12d1c3fa352026)的含义吗
```
        poses.append(
            np.matmul(Tr_inv, np.matmul(pose, Tr))
        )  # lidar pose in world frame
```

**Comment by YuePanEdward** [comment]
> > You can try to add [this](https://gist.github.com/YuePanEdward/c8f83e65191ea02fcf12d1c3fa352026) to common.py.
> > And then replace `xyz_np, sensor_np = load_waymo_example()` with `xyz_np, sensor_np = load_kitti_like_data(pc_folder, pose_file, calib_file, every_n_frame=1, begin_frame=0, end_frame=100)` and provide the correct path to your dataset.
> > For the visualization, you may use open3d:
> > ```
> > import open3d as o3d
> > mesh_v, mesh_f = mesh.v.detach().cpu().numpy(), mesh.f.detach().cpu().numpy()
> > mesh = o3d.geometry.TriangleMesh(o3d.utility.Vector3dVector(mesh_v), o3d.utility.Vector3iVector(mesh_f))
> > mesh.compute_vertex_normals()
> > o3d.visualization.draw_geometries([mesh])
> > o3d.io.write_triangle_mesh(your_mesh_path, mesh)
> > ```
> 
> 您好请问一下，能解释一下[这段代码](https://gist.github.com/YuePanEdward/c8f83e65191ea02fcf12d1c3fa352026)的含义吗
> 
> ```
>         poses.append(
>             np.matmul(Tr_inv, np.matmul(pose, Tr))
>         )  # lidar pose in world frame
> ```

You may check the explanation here: https://github.com/PRBonn/kiss-icp/issues/156#issuecomment-1551695713, which should be similar to the issue here.

**Comment by heiwang1997** [comment]
@YuePanEdward The results look amazing! For the marching cubes implementation, please refer to the code [here](https://github.com/huangjh-pub/neural-galerkin/tree/pth/csrc/marching_cubes). Thank you! 🍉

**Comment by rockywind** [comment]
Hi, @heiwang1997 
How to use the marching cubes implemention?
Have a example code?
The below is my own data result. How can I improve it?
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/d7b8b873-b786-4942-9162-3ef6ea067d73)

**Comment by heiwang1997** [comment]
Yes, you can check out [here](https://github.com/huangjh-pub/neural-galerkin/blob/5ec184004edbbf7492e49167d5063ac16712f629/torch_spsr/core/reconstructor.py#L295) for example code.

Have you tried out the tricks that we talked about in the previous messages? What does the input point cloud look like?

**Comment by rockywind** [comment]
Hi, 
This is my setting.

![image](https://github.com/nv-tlabs/NKSR/assets/14838781/8bd60fc1-e920-454a-b852-46201708d91b)
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/ef6d5b34-4d2f-4c3f-9cd0-fb4d085f08fa)
The below is my new result.
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/568314ef-ed3a-46bf-86b3-e69cae213a13)
My dataset is paking data. Can I finetune the model on my own data?
The performance of reconstruction can improve when I finetune?

**Comment by heiwang1997** [comment]
Hey I'm not sure if everything is correctly set up here, and from your result it seems that parts of the ground are flipped. This could either be because your sensor positions are not accurate, or your point cloud contains too much noise, so our model fails to handle such cases.
To fine-tune the model, you will need ground-truth geometry and we use the CARLA dataset for that -- it's available in the README. Feel free to check that out.
Have you tried out the tricks that we talked about in the previous messages? What does the input point cloud look like?

**Comment by zgojcic** [comment]
Hi [rockywind](https://github.com/rockywind)

Considering that this is parking data, the point cloud on the ground is probably very sparse because the ego-car doesn't move at all or only slightly. In such cases, you are left with individual scan lines on the ground, for which it is very hard to estimate the normals correctly. Could you maybe visualize the input point cloud?

**Comment by rockywind** [comment]
Hi,all
This is the visualization of the input point cloud.
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/3679a152-1671-42b3-9e15-dd0e709cc4ed)
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/dbe64e0e-9922-48e2-ab83-ec9473e1ae96)

**Comment by rockywind** [comment]
Hi, @heiwang1997 
当我调大sensor的Z+2值时候，重建的mesh会往上补全。
![image](https://github.com/nv-tlabs/NKSR/assets/14838781/8581b25b-7d67-4041-868c-7cbcb0236967)

**Comment by heiwang1997** [comment]
Interesting... would you mind send me your file and let me investigate into it a bit?
I think I will just need the XYZ + sensor array that you've generated

**Comment by JIANG-CX** [comment]
> @YuePanEdward The results look amazing! For the marching cubes implementation, please refer to the code [here](https://github.com/huangjh-pub/neural-galerkin/tree/pth/csrc/marching_cubes). Thank you! watermelon

Hello, when I run tests on the KITTI dataset, I'm encountering an OOM (Out of Memory) error during the marching cube process (dual_v, dual_f = MarchingCubes().apply(dmc_graph, dmc_vertices.cuda(), dmc_value.cuda())). I'm wondering if there's a way to perform marching cubes on the dataset in chunks to reduce memory consumption. Could you please advise on how to achieve this? Thanks.

**Comment by leslieburke** [comment]
@heiwang1997 想请问一下sensor array里面给的是什么信息啊

**Comment by heiwang1997** [comment]
是每个点对应的传感器位置，即采集这个点的时候，传感器的xyz世界坐标～

**Comment by leslieburke** [comment]
@heiwang1997 再请教一下，我跑的时候报out of memory了，我有两张gpu，能不能用两张gpu来跑这个重建？另外参考readme里的内容，把
field.to_("cpu")
reconstructor.network.to("cpu")
这两句话取消注释，会报错
RuntimeError: (*grid) and query are not on the same device!

**Comment by heiwang1997** [comment]
如果要用两个GPU的话，需要把input事先切成两块，然后分别输入每个GPU对应的Reconstructor
关于第二个错误，能麻烦发下完整的代码吗？我测试一下

**Comment by leslieburke** [comment]
> 如果要用两个GPU的话，需要把input事先切成两块，然后分别输入每个GPU对应的Reconstructor 关于第二个错误，能麻烦发下完整的代码吗？我测试一下

就是您example里的代码

    device = torch.device("cuda:0")
    reconstructor = nksr.Reconstructor(device)
    reconstructor.chunk_tmp_device = torch.device("cpu")

    input_xyz = torch.from_numpy(xyz_np).float().to(device)
    input_sensor = torch.from_numpy(sensor_np).float().to(device)

    field = reconstructor.reconstruct(
        input_xyz, sensor=input_sensor, detail_level=None,
        # Minor configs for better efficiency (not necessary)
        approx_kernel_grad=True, solver_tol=1e-4, fused_mode=True,
        # Chunked reconstruction (if OOM)
        chunk_size=50,
        preprocess_fn=nksr.get_estimate_normal_preprocess_fn(64, 85.0)
    )

    # (Optional) Convert to CPU for mesh extraction
    field.to_("cpu")
    reconstructor.network.to("cpu")

    mesh = field.extract_dual_mesh(mise_iter=1)
    mesh = vis.mesh(mesh.v, mesh.f)

**Comment by heiwang1997** [comment]
您好，我运行您的代码的时候提示找不到`xyz_np`和`sensor_np`变量，能烦请您发一下完整的代码吗？谢谢！

另外，如果直接运行 `python examples/recons_waymo.py`，我这里是不会报错的

**Comment by leslieburke** [comment]
> 您好，我运行您的代码的时候提示找不到`xyz_np`和`sensor_np`变量，能烦请您发一下完整的代码吗？谢谢！
> 
> 另外，如果直接运行 `python examples/recons_waymo.py`，我这里是不会报错的

我这个代码上面读数据的load函数是我自己写的，读的我自己的数据，所以没放上来

我把examples/recons_waymo.py中的
field.to_("cpu")
reconstructor.network.to("cpu")
取消注释的话，还是会报错

![2023-07-06 10-33-55屏幕截图](https://github.com/nv-tlabs/NKSR/assets/107837070/b737ffae-ed81-401c-8db7-718de018a03f)

**Comment by heiwang1997** [comment]
可以print一下nksr的版本吗？`print(nksr.__version__)`

**Comment by leslieburke** [comment]
> 可以print一下nksr的版本吗？`print(nksr.__version__)`

1.0.0+pt20cu118

**Comment by heiwang1997** [comment]
谢谢，请您安装最新版本的nksr：

```bash
pip install -U nksr -f https://nksr.huangjh.tech/whl/torch-2.0.0+cu118.html
```

**Comment by jeremycp3** [comment]
您好，请问可以将点云的深度信息加进去吗

**Comment by YoushaaMurhij** [comment]
> You can try to add [this](https://gist.github.com/YuePanEdward/c8f83e65191ea02fcf12d1c3fa352026) to common.py.
> 
> And then replace `xyz_np, sensor_np = load_waymo_example()` with `xyz_np, sensor_np = load_kitti_like_data(pc_folder, pose_file, calib_file, every_n_frame=1, begin_frame=0, end_frame=100)` and provide the correct path to your dataset.
> 
> For the visualization, you may use open3d:
> 
> ```
> import open3d as o3d
> mesh_v, mesh_f = mesh.v.detach().cpu().numpy(), mesh.f.detach().cpu().numpy()
> mesh = o3d.geometry.TriangleMesh(o3d.utility.Vector3dVector(mesh_v), o3d.utility.Vector3iVector(mesh_f))
> mesh.compute_vertex_normals()
> o3d.visualization.draw_geometries([mesh])
> o3d.io.write_triangle_mesh(your_mesh_path, mesh)
> ```

@YuePanEdward  @rockywind  I tried this visualization script and got a gray mesh. Could you please tell me how to add the original intensity colors to the mesh or any other similar feature?
Thanks

**Comment by sifanxian** [comment]
请问这个可以使用colmap中SFM的结果作为输入吗?

**Comment by heiwang1997** [comment]
SFM points from COLMAP don't have normal information and could be too sparse. Alternatively you could take the oriented point cloud from a typical MVG pipeline (e.g. from https://github.com/openMVG/openMVG) and replace the Poisson reconstruction with NKSR :)

**Comment by sifanxian** [comment]
> Alternatively you could take the oriented point cloud from a typical MVG pipeline

OK，Thank you for your reply, I'll try it.

**Comment by hungdche** [comment]
> I've got some quite good results on KITTI and Newer College datasets using NKSR and the reconstruction is also super fast (in about 10 seconds) ![Screenshot from 2023-06-12 15-04-28](https://user-images.githubusercontent.com/34207278/245153736-99ef94d1-5974-47ef-b187-79dfe5c37ce0.png) ![Screenshot from 2023-06-12 15-08-02](https://user-images.githubusercontent.com/34207278/245153814-95f67570-39e3-4577-88a3-96a111c4abfe.png)

Hi @YuePanEdward, sorry for digging this up. I'm trying to run NKSR on KITTI seq 0 and for some reason mine does not look as good as yours 

![image](https://github.com/nv-tlabs/NKSR/assets/90811347/03a38b24-de4d-4b77-89e1-d178d6571788)

I'm just asking if you use the defaults parameter as followed
```
field = reconstructor.reconstruct(
        input_xyz, sensor=input_sensor, detail_level=None,
        # Minor configs for better efficiency (not necessary)
        approx_kernel_grad=True, solver_tol=1e-4, fused_mode=True,
        # Chunked reconstruction (if OOM)
        chunk_size=51.2,
        preprocess_fn=nksr.get_estimate_normal_preprocess_fn(64, 85.0)
    )
```
Thanks in advance!
