### ISSUE TITLE
NKSR deploy in lower version of cuda？

### ISSUE THREAD

**Issue by Saixiaoma** [nv-tlabs/NKSR#30]
Hi, Can the NKSR library support a lower version of cuda? For example cuda11.3.

**Comment by heiwang1997** [comment]
Yes, it can. The CUDA version is actually determined by your pytorch installation, instead of your system cuda.
You can select the correct version of NKSR to install based on [this page](https://github.com/nv-tlabs/NKSR/blob/public/NKSR-USAGE.md), where cu113 is available for pytorch 1.12.0.

**Comment by Saixiaoma** [comment]
Thanks a lot
