### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by TichiBichi** [nv-tlabs/NKSR#36]
Total newbie here. I really want to join the sweepstakes as I have some good LiDAR scans. I cloned the repository and when I try to create an environment using Anaconda  Prompt I get the following message:
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - gxx_linux-64=11
  - gcc_linux-64=11

And if I try to install gxx_linux and gcc_linux I get the same message for both:

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - gcc_linux-64

I know I could also install it with Docker but I also don't know how. I would really appreciate the help. Thanks in advance!

**Comment by heiwang1997** [comment]
Hi sorry for the late response! I never met this problem before. Could you try either upgrading your conda or simply removing these two dependencies from the `environment.yml` file?
