### ISSUE TITLE
LAS Point cloud support

### ISSUE THREAD

**Issue by fwilliams** [nv-tlabs/NKSR#39]
I've been asked a few times about this -- it would be nice to support [LAS ](https://www.loc.gov/preservation/digital/formats/fdd/fdd000418.shtml#:~:text=LAS%20is%20a%20file%20format,radar%2C%20RAdio%20Detection%20and%20Ranging.)inputs at some point:

**Comment by heiwang1997** [comment]
I've gone through the documentation that you sent. Does LAS offer us (meta) information other than just xyz (and sensor positions)?

**Comment by fwilliams** [comment]
The docs for laspy are better: https://laspy.readthedocs.io/en/latest/intro.html

**Comment by heiwang1997** [comment]
Thanks!! So I think we could just store the meta information (such as projection) along with the reconstructed mesh? What change do we need in NKSR's codebase to support LAS? It's just a new data reader other than open3d right?

**Comment by TokyoWarfare** [comment]
So, if I've the mobile mapping scan data in .las tiles what should I do? because the input seems to need the normals and points as separate inputs.

**Comment by heiwang1997** [comment]
You could refer to the newest example on las file under the folder `examples/`
