### ISSUE TITLE
Could you please provide a pre-trained weight that does not require normal vectors or sensor vectors? Thanks.

### ISSUE THREAD

**Issue by advancing-panda** [nv-tlabs/NKSR#42]
Could you please provide a pre-trained weight that does not require normal vectors or sensor vectors? Thanks.

**Comment by advancing-panda** [comment]
Is it true that the weights downloaded from https://nksr.huangjh.tech/snet-n3k-wonormal.pth do not require normal vectors or sensor vectors?

**Comment by advancing-panda** [comment]
OK! I know it. Thank you very much.

**Comment by heiwang1997** [comment]
Oh yes it does :) also sorry for the late reply. But that model is trained only on ShapeNet dataset. I'm not sure how well it will perform on your own data.
