### ISSUE TITLE
The influence of dynamic object point clouds on the reconstruction results

### ISSUE THREAD

**Issue by qixuema** [nv-tlabs/NKSR#5]
Thank you very much for your outstanding work. This work is amazing. 

I have a question I would like to ask. When using LiDAR point clouds to reconstruct street scenes, there are often many dynamic objects in the point clouds. These objects generate numerous continuous point clouds during their movement. Have you considered how to solve this problem?

![image](https://github.com/nv-tlabs/NKSR/assets/58554118/469293d7-b0da-4907-a9c9-81e8132b0198)

**Comment by fwilliams** [comment]
The current model does not remove dynamic points which causes the artifacts that you are seeing! A neat extension would be to fine tune tune the kitchen sink model to predict dynamic labels and then exclude those points from the input. If you have these in your data set this wouldn't be too hard to do and would be a great contribution!

**Comment by heiwang1997** [comment]
Yeah agreed. The tail-like geometry would be relatively easy to be segmented out if the model is focused on AV scenes only, and we definitely should think about future works that handle them all. If you want to find a technique that explicitly tackles dynamic objects, please check out this paper as a starting point: https://github.com/prs-eth/PCAccumulation. Thanks!

**Comment by qixuema** [comment]
Thank you so much for your response.
I will look deeper into this work:  https://github.com/prs-eth/PCAccumulation.
Finally, thank you again. 🙏
