### ISSUE TITLE
SSL certificate expired for nksr.huangjh.tech

### ISSUE THREAD

**Issue by zfb132** [nv-tlabs/NKSR#51]
I'd like to express my appreciation for your project, and I'm grateful for your work and contributions.

I have noticed that the SSL certificate for `nksr.huangjh.tech` expired on November 18, 2023. I suggest implementing an automated SSL certificate renewal process using tools such as [acme.sh](https://github.com/acmesh-official/acme.sh) or [certbot](https://github.com/certbot/certbot).

Due to the expired certificate, other users might encounter security warnings when installing the `nksr` library. I have a temporary workaround.
```bash
# Install NKSR
# pip install nksr -f https://nksr.huangjh.tech/whl/torch-2.0.0+cu118.html
pip install nksr -f https://nksr.s3.ap-northeast-1.amazonaws.com/whl/torch-2.0.0%2Bcu118.html

# Download pre-trained model before running any code
wget --no-check-certificate "https://nksr.huangjh.tech/ks.pth" -O ~/.cache/torch/hub/checkpoints/ks.pth
```

**Comment by glennliu** [comment]
@zfb132  Thanks for your kind advice. I was trying to install the pip dependency, 
```python
pip install python-pycg[full]==0.5.2 -i https://pycg.huangjh.tech/packages/index.html --trusted-host pycg.huan
gjh.tech 
```
And it outputs,
```bash
Looking in indexes: https://pycg.huangjh.tech/packages/index.html
ERROR: Could not find a version that satisfies the requirement python-pycg==0.5.2 (from versions: none)
ERROR: No matching distribution found for python-pycg==0.5.2
```
Do you know is it also relates with the SSL certification issue?

Thanks

**Comment by zfb132** [comment]
@glennliu No, it is not related to the SSL certificate. You can ignore the SSL certificate by using `--trusted-host pycg.huangjh.tech`. I think you should use `-f`, not `-i`.  

`pip install python-pycg[full]==0.5.2 -f https://pycg.huangjh.tech/packages/index.html --trusted-host pycg.huangjh.tech`
