### ISSUE TITLE
POCO results in Table1

### ISSUE THREAD

**Issue by ghzcx01** [nv-tlabs/NKSR#55]
Thanks for your great work! I have a question about the POCO results in Table1. The numbers seem a bit different from the original POCO paper. Is that because of adding normal to the training?

**Comment by heiwang1997** [comment]
Hey yes exactly. All of our reported numbers are obtained by following the training procedure of the baselines, while we align the input to be the same (either point only or point + normal).

Please let me know if you need the specific metric numbers. Actually, @matanatz ran this experiment -- feel free to add anything that I'm missing :)
