### ISSUE TITLE
AttributeError: partially initialized module 'nksr' has no attribute 'Reconstructor' (most likely due to a circular import)

### ISSUE THREAD

**Issue by zhouilu** [nv-tlabs/NKSR#60]
I saw a similar issue, but I still haven't solved it.

My torch version is 2.0.0 and CUDA version is 11.8, and i download model from https://nksr.huangjh.tech/ks.pth.
 can you give me some advice?

nksr  vision: 1.0.3+pt20cu118
torch vision: 2.0.0+cu118

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nksr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/nksr.py", line 7, in <module>
    reconstructor = nksr.Reconstructor(device)
AttributeError: partially initialized module 'nksr' has no attribute 'Reconstructor' (most likely due to a circular import)

**Comment by dnabanita7** [comment]
Same, I am also getting the similar issue: pytorch version is 2.1.2 and cuda version is 12.1.

**Comment by zhouilu** [comment]
> Same, I am also getting the similar issue: pytorch version is 2.1.2 and cuda version is 12.1.

your version is not compatible

**Comment by zhouilu** [comment]
sorry, my own problem, so close it.
