### ISSUE TITLE
Coordinate system of the output mesh

### ISSUE THREAD

**Issue by Dharmendra04** [nv-tlabs/NKSR#68]
I plan to supervise my own  model using normal supervision. To achieve this, I am using the point cloud obtained from COLMAP and feeding it, along with the normals, to your model. However, when I extracted the vertices and normals using open3d, I noticed that the surface reconstruction generated more points compared to my original point cloud from COLMAP. Specifically, the number of mesh vertices was greater than the number of points in the initial point cloud.

Is the coordinate system of the mesh vertices the same as my COLMAP point cloud reference system?

"Will the original point cloud also be converted into one of the vertices?"

As I have some specific requirements only for the initial point cloud points, I need to extract the normals obtained from your model and apply them to the same point clouds' points. Can you please advise me on how to do that?

**Comment by heiwang1997** [comment]
Hi thank you for your question. Currently we don't have any guarantee that the #vertices of the mesh = #input points. However, the coordinate system should match. 

> "Will the original point cloud also be converted into one of the vertices?"

So for this the answer would be no.

>  I need to extract the normals obtained from your model and apply them to the same point clouds' points. Can you please advise me on how to do that?

Yes what you can do is to find the nearest surface position (of the reconstructed mesh) from each of your input point cloud. All these could be easily implemented via PCU (https://www.fwilliams.info/point-cloud-utils/). A related tutorial is https://www.fwilliams.info/point-cloud-utils/sections/closest_point_on_mesh/.

Hope this helps!!

**Comment by Dharmendra04** [comment]
Thank you very much.

**Comment by Dharmendra04** [comment]
I will close this issue
