### ISSUE TITLE
About nksr module

### ISSUE THREAD

**Issue by YZWYD** [nv-tlabs/NKSR#71]
Hello, I would like to apply your NKSR project to the Jetson (aarch64 architecture) platform, but the download link you provided only has versions compatible with the linux_x86-64 architecture. Could you please share a version suitable for the aarch64 architecture? Or could you provide the source code for compilation and installation?

**Comment by heiwang1997** [comment]
Hi yes! The full code is now released at https://github.com/nv-tlabs/XCube/tree/main/ext/nksr-cuda.
We are working on publishing pip packages and hopefully will have everything officially released by August ;)

**Comment by chgarner** [comment]
@YZWYD Were you able to complete the NKSR compilation for the Jetson? I also want to use the project on the Jetson Platform.
