### ISSUE TITLE
Cannot install nksr package due to the "certificate has expired" error 

### ISSUE THREAD

**Issue by ShudaLi** [nv-tlabs/NKSR#72]
$ pip install nksr -f https://nksr.huangjh.tech/whl/torch-2.0.0+cu118.html
Looking in links: https://nksr.huangjh.tech/whl/torch-2.0.0+cu118.html
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)'))': /whl/torch-2.0.0+cu118.html
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)'))': /whl/torch-2.0.0+cu118.html
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)'))': /whl/torch-2.0.0+cu118.html
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)'))': /whl/torch-2.0.0+cu118.html
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)'))': /whl/torch-2.0.0+cu118.html
Could not fetch URL https://nksr.huangjh.tech/whl/torch-2.0.0+cu118.html: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='nksr.huangjh.tech', port=443): Max retries exceeded with url: /whl/torch-2.0.0+cu118.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)'))) - skipping

**Comment by heiwang1997** [comment]
Hi sorry this should now be fixed!
