### ISSUE TITLE
Questions about Training  Process

### ISSUE THREAD

**Issue by Gy920** [nv-tlabs/NKSR#74]
Hi,

Thank you for your outstanding work. I have a few questions regarding the **training** process:

1. **Training Time**:
   - How long does it typically take to train on the ShapeNet and Points2Surf datasets?

2. **Batch Size Limitation**:
    - I noticed that the batch size on a single GPU can only be set to **1**. Are there any methods or configurations that could allow for a **larger batch size**?

Thanks for your help!

**Comment by heiwang1997** [comment]
Training time -- it took ~4-5 days to train on ShapeNet on a single V100. Points2Surf is easier and takes ~2 days to converge.

Batch size -- good point and we release the batched version here at: https://github.com/nv-tlabs/XCube/tree/main/ext/nksr-cuda.

Currently we're pending an internal schedule so there's not a lot of documentation on that. I will update things hopefully in the beginning of August to incorporate that.

Thanks!!!

**Comment by Gy920** [comment]
Thanks for your reply. I have no further questions.
